version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Python.Dockerfile
    command: python check_blocked.py
    cpus: '0.5'
    mem_limit: '1gb'
    shm_size: '1gb'
    volumes:
      - ./app:/app
